Repository AT-PHPIntership/food-drink, pull requests merged in 2018-07, with the labels that each got.

#188 fix-bug admin
  public/js/user/showProfileUser.js
  resources/views/admin/category/index.blade.php
Labels: bug, in-review, week 7

#191 layout get history orders
  app/Http/Controllers/User/OrderController.php
  public/css/user/add.css
  public/js/user/masterPage.js
  resources/lang/en/home.php
  resources/lang/en/order.php
  resources/views/user/layout/header.blade.php
  resources/views/user/order/index.blade.php
  routes/web.php
Labels: in-review, task, week 7

#195 edit column address in table order_details and fix seed,factory,show …
  app/Order.php
  app/OrderDetail.php
  database/factories/ModelFactory.php
  database/migrations/2018_07_01_082100_remove_order_details_column.php
  database/migrations/2018_07_01_082346_add_orders_column.php
  database/seeds/OrderDetailsTableSeeder.php
  database/seeds/OrdersTableSeeder.php
  resources/views/admin/order/show.blade.php
  tests/Browser/Pages/Backend/Order/ShowDetailOrderTest.php
Labels: in-review, task, week 7

#193 fix document api show orders
  docs/api-references/order.md
Labels: in-review, task, week 7

#192 use api delete post
  public/frontend/css/add.css
  public/js/user/showPostOfProduct.js
  public/js/user/userLogin.js
Labels: in-review, task, week 7

#190 document add order
  app/Order.php
  docs/api-references/order.md
Labels: in-review, task, week 7

#196 Use api show orders
  app/Http/Controllers/Api/OrderController.php
  app/Order.php
  docs/api-references/order.md
  public/js/messages.js
  public/js/user/showHistoryOrders.js
  resources/lang/en/order.php
  resources/views/user/order/index.blade.php
Labels: in-review, task, week 7

#197 update layout description product ckeditor
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/edit.blade.php
  resources/views/admin/product/show.blade.php
  tests/Browser/Pages/Backend/Product/CreateProductTest.php
  tests/Browser/Pages/Backend/Product/EditProductTest.php
  tests/CreatesApplication.php
Labels: in-review, task, week 7

#199 write api show order detail
  app/Http/Controllers/Api/OrderController.php
  routes/api.php
Labels: in-review, task, week8

#200 write document api delete order
  docs/api-references/order.md
Labels: in-review, task, week8

#201 layout show order detail
  app/Http/Controllers/User/OrderController.php
  public/js/user/showHistoryOrders.js
  resources/lang/en/order.php
  resources/views/user/order/show.blade.php
  routes/web.php
Labels: in-review, task, week8

#202 fix layout when login
  public/css/user/add.css
  public/js/user/masterPage.js
  resources/lang/en/cart.php
  resources/views/user/cart/index.blade.php
Labels: in-review, task, week8

#203 edit route order
  public/js/user/showHistoryOrders.js
  resources/views/user/cart/index.blade.php
  resources/views/user/layout/header.blade.php
  routes/web.php
Labels: in-review, task, week8

#194 use api and fix api filter product by name product
  app/Http/Controllers/Api/ProductController.php
  public/frontend/css/add.css
  public/js/user/showListProducts.js
  resources/lang/en/sidebar.php
  resources/views/user/layout/sidebar.blade.php
Labels: in-review, task, week 7

#204 Use api order detail
  app/OrderDetail.php
  public/js/user/showOrderDetails.js
  resources/views/user/layout/script.blade.php
  resources/views/user/order/show.blade.php
  resources/views/user/product/index.blade.php
Labels: in-review, task, week8

#207 view cart order
  public/js/messages.js
  public/js/user/viewCartOrder.js
  resources/lang/en/order.php
  resources/views/user/order/create.blade.php
Labels: in-review, task, week8

#210 api add order
  app/Http/Controllers/Api/OrderController.php
  app/Http/Requests/Api/CreateOrderRequest.php
  app/OrderDetail.php
  database/factories/ModelFactory.php
  database/migrations/2018_07_03_101103_remove_preview_to_order_details_table.php
  database/seeds/OrderDetailsTableSeeder.php
  resources/views/admin/order/show.blade.php
  routes/api.php
Labels: in-review, task, week8

#208 paginate all product
  public/frontend/css/add.css
  public/js/user/showListProducts.js
  resources/lang/en/product.php
  resources/views/user/product/index.blade.php
Labels: in-review, task, week8

#209 show cart in header
  public/js/user/addCart.js
  public/js/user/masterPage.js
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/sidebar.blade.php
Labels: in-review, task, week8

#206 api cancel order
  app/Http/Controllers/Api/OrderController.php
  app/Http/Requests/Api/CreateNoteRequest.php
  app/Note.php
  app/OrderDetail.php
  resources/lang/en/errors.php
  routes/api.php
Labels: in-review, task, week8

#211 Use api add order
  app/OrderDetail.php
  public/js/user/addCart.js
  public/js/user/showListProducts.js
  public/js/user/showProductHomePage.js
  public/js/user/viewCartOrder.js
Labels: in-review, task, week8

#214 Paginate order
  public/js/user/showHistoryOrders.js
  resources/views/user/order/index.blade.php
Labels: in-review, task, week8

#213 layout update user
  app/Http/Controllers/User/UserController.php
  resources/lang/en/home.php
  resources/lang/en/profile.php
  resources/views/user/profile/update.blade.php
  resources/views/user/profile/userProfile.blade.php
  routes/web.php
Labels: in-review, task, week8

#215 paginate order detail
  public/js/user/showHistoryOrders.js
  public/js/user/showOrderDetails.js
  resources/views/user/order/show.blade.php
Labels: in-review, task, week8

#216 fix bug login and order
  app/Order.php
  public/js/user/masterPage.js
  public/js/user/showHistoryOrders.js
  public/js/user/showPostOfProduct.js
  resources/views/user/layout/header.blade.php
Labels: in-review, task, week8

#217 Paginate post
  public/js/user/showPostOfProduct.js
  resources/views/user/order/create.blade.php
  resources/views/user/order/index.blade.php
  resources/views/user/order/show.blade.php
  resources/views/user/product/show.blade.php
  resources/views/user/profile/update.blade.php
Labels: in-review, task, week8

#219 docs edit order and change index list order
  docs/api-references/order.md
  public/js/user/showHistoryOrders.js
  resources/views/user/order/index.blade.php
Labels: in-review, task, week8

#218 use api update user
  app/Http/Controllers/Api/ProfileController.php
  app/Http/Requests/Api/UpdateProfileRequest.php
  public/js/user/editUser.js
  resources/views/user/profile/update.blade.php
Labels: in-review, task, week8

#220 use api cancel order and edit document, api cancel order
  app/Http/Controllers/Api/OrderController.php
  docs/api-references/order.md
  public/frontend/css/add.css
  public/js/messages.js
  public/js/user/showHistoryOrders.js
  resources/lang/en/order.php
  resources/views/user/order/index.blade.php
  routes/api.php
Labels: in-review, task, week8

#221 api-edit-order
  app/Http/Controllers/Api/OrderController.php
  routes/api.php
Labels: in-review, task, week8

#222 show info category
  app/Http/Controllers/Admin/CategoriesController.php
  resources/lang/en/category.php
  resources/views/admin/category/index.blade.php
  resources/views/admin/category/show.blade.php
  routes/web.php
Labels: bug, task, week8

#227 add layout edit order and fix layout create order
  app/Http/Controllers/User/OrderController.php
  public/js/messages.js
  public/js/user/showHistoryOrders.js
  public/js/user/viewCartOrder.js
  resources/lang/en/order.php
  resources/views/user/order/edit.blade.php
  routes/web.php
Labels: in-review, task, week8

#224 bug admin and change font end user
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  public/frontend/images/banner_drink.jpg
  public/frontend/images/banner_food.jpg
  public/frontend/images/drink.jpg
  public/frontend/images/logo.png
  resources/views/user/home/index.blade.php
  resources/views/user/layout/sidebar.blade.php
Labels: bug, task, week8

#228 layout-forgot-password
  app/Http/Controllers/Home/ForgotPasswordController.php
  app/Http/Controllers/Home/ResetPasswordController.php
  resources/lang/en/forgot-password.php
  resources/lang/en/home.php
  resources/views/public/pages/new-password.blade.php
  resources/views/public/pages/reset-password.blade.php
  resources/views/user/layout/header.blade.php
  routes/web.php
Labels: in-review, task, week 9

#229 edit document order, api, use api show order detail
  app/Http/Controllers/Api/OrderController.php
  docs/api-references/order.md
  public/js/user/showOrderDetails.js
Labels: in-review, task, week 9

#225 fix update order user
  app/Http/Controllers/Api/OrderController.php
Labels: bug, in-review, week8

#212 write unit test api edit user
  tests/Feature/Api/EditUserTest.php
  tests/Feature/Api/ListProductTest.php
  tests/TestCase.php
Labels: in-review, task, week8

#231 fix layout page user
  public/frontend/css/add.css
  public/frontend/images/flag-english.jpg
  public/frontend/images/flag-vietnam.png
  public/js/user/addCart.js
  public/js/user/masterPage.js
  public/js/user/viewCartOrder.js
  resources/lang/en/cart.php
  resources/lang/en/home.php
  resources/views/user/layout/header.blade.php
Labels: in-review, task, week 9

#234 Unit test api show order
  tests/Feature/Api/EditUserTest.php
  tests/Feature/Api/ListOrderTest.php
Labels: in-review, task, week 9

#232 Use api forgot password
  public/js/messages.js
  public/js/user/forgotPassword.js
  resources/lang/en/forgot-password.php
  resources/views/public/pages/login.blade.php
  resources/views/public/pages/new-password.blade.php
  resources/views/public/pages/reset-password.blade.php
  resources/views/user/layout/header.blade.php
Labels: in-review, task, week 9

#237 Translate vi
  app/Http/Kernel.php
  app/Http/Middleware/Language.php
  public/frontend/css/add.css
  public/js/messages.js
  public/js/user/masterPage.js
  public/js/user/showProductDetail.js
  resources/lang/vi/api.php
  resources/lang/vi/cart.php
  resources/lang/vi/errors.php
  resources/lang/vi/forgot-password.php
  resources/lang/vi/home.php
  resources/lang/vi/login.php
  resources/lang/vi/message.php
  resources/lang/vi/order.php
  resources/lang/vi/product.php
  resources/lang/vi/profile.php
  resources/lang/vi/sidebar.php
  resources/lang/vi/user.php
  resources/views/public/pages/login.blade.php
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/sidebar.blade.php
  routes/web.php
Labels: in-review, task, week 9

#236 Unit test api cancel order
  app/Http/Controllers/Api/OrderController.php
  docs/api-references/order.md
  tests/Feature/Api/CancelOrderTest.php
Labels: in-review, task, week 9

#239 docs recommend
  docs/api-references/product.md
  resources/views/api-docs.blade.php
Labels: in-review, task, week 9

#240 create table, seeder, factory shipping
  app/Shipping.php
  app/User.php
  database/factories/ModelFactory.php
  database/migrations/2018_07_12_071856_create_shippings_table.php
  database/seeds/DatabaseSeeder.php
Labels: in-review, task, week 9

#238 api-login-facebook
  app/Http/Controllers/User/SocialAuthController.php
  app/Services/SocialAccountService.php
  app/User.php
  app/UserInfo.php
  composer.json
  composer.lock
  config/app.php
  config/services.php
  database/migrations/2018_07_11_074406_add_null_users_and_user_info_table.php
  database/migrations/2018_07_11_080123_add_social_provider_to_users_table.php
  resources/lang/en/login.php
  resources/views/public/pages/login.blade.php
  routes/web.php
Labels: in-review, task, week 9

#243 edit document, api and use api user profile
  app/Http/Controllers/Api/ProfileController.php
  docs/api-references/user.md
  public/frontend/css/add.css
  public/js/user/showProfileUser.js
  resources/lang/en/user.php
  resources/lang/vi/user.php
  resources/views/user/profile/userProfile.blade.php
Labels: in-review, task, week 10

#242 admin user info
  app/Http/Controllers/Admin/UsersController.php
  resources/lang/en/user.php
  resources/views/admin/user/index.blade.php
  resources/views/admin/user/show.blade.php
  tests/Browser/Pages/Backend/User/EditUserTest.php
Labels: in-review, task, week 10

#246 fix use api profile, use edit profile and add default address
  database/factories/ModelFactory.php
  database/migrations/2018_07_16_084023_add_default_address_to_shippings_table.php
  public/frontend/css/add.css
  public/js/user/editUser.js
  public/js/user/showProfileUser.js
  resources/lang/en/profile.php
  resources/lang/vi/profile.php
  resources/views/user/profile/update.blade.php
Labels: in-review, task, week 10

#233 Use api edit order and edit use api show order
  app/Http/Requests/Api/SortOrderRequest.php
  public/frontend/css/add.css
  public/js/user/editOrder.js
  public/js/user/showHistoryOrders.js
  public/js/user/viewCart.js
  resources/lang/en/order.php
  resources/views/user/order/edit.blade.php
Labels: in-review, task, week 9

#150 Unit test api show posts
  tests/Feature/Api/ShowPostTest.php
Labels: in-review, task, week6

#247 lay out compare product
  app/Http/Controllers/User/ProductController.php
  resources/lang/en/product.php
  resources/lang/vi/product.php
  resources/views/user/product/compare.blade.php
  routes/web.php
Labels: in-review, task, week 10

#245 Use api recommend product
  public/js/user/recommendProduct.js
  public/js/user/showListProducts.js
  public/js/user/showProductDetail.js
  resources/lang/en/product.php
  resources/lang/vi/product.php
  resources/views/user/product/show.blade.php
Labels: in-review, task, week 10

#250 edit api and request update profile
  app/Http/Controllers/Api/ProfileController.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Requests/Api/UpdateProfileRequest.php
  app/Http/Requests/StoreUsers.php
Labels: in-review, task, week 10

#248 fix bug add order
  public/js/messages.js
  public/js/user/showListProducts.js
  public/js/user/showProductHomePage.js
  public/js/user/viewCartOrder.js
  resources/lang/en/product.php
  resources/lang/vi/product.php
Labels: in-review, task, week 10

#253 edit document create order
  docs/api-references/order.md
Labels: in-review, task, week 10

#257 fix document edit profile when set default address
  docs/api-references/user.md
Labels: in-review, task, week 10

#255 create table, model tracking order and fix model shippings, order
  app/Order.php
  app/Shipping.php
  app/TrackingOrder.php
  database/migrations/2018_07_18_093542_create_tracking_orders_table.php
Labels: in-review, task, week 10

#259 Add time when change status
  app/Http/Controllers/Admin/OrdersController.php
  app/Http/Controllers/Api/OrderController.php
Labels: in-review, task, week 10

#251 docs create shipping address
  docs/api-references/ship.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week 10

#258 send mail recommend product
  app/Console/Commands/SendEmailRecommend.php
  app/Console/Kernel.php
  app/Jobs/SendEmailRecommendJob.php
  app/Mail/SendEmailRecommends.php
  resources/views/email/send-mail-recommend.blade.php
Labels: in-review, task, week 10
