Repository AT-PHPIntership/food-drink, pull requests merged in 2018-05, with the labels that each got.

#6 add templates admin home
  .bowerrc
  app/Http/Controllers/Admin/HomeController.php
  package-lock.json
  package.json
  resources/views/admin/home/index.blade.php
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/layout/sidebar.blade.php
  routes/web.php
Labels: in-review, task, week1

#7 Seeder
  database/seeds/CategoriesTableSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ImagesTableSeeder.php
  database/seeds/OrderDetailsTableSeeder.php
  database/seeds/OrdersTableSeeder.php
  database/seeds/PostsTableSeeder.php
  database/seeds/ProductsTableSeeder.php
  database/seeds/UserInfosTableSeeder.php
  database/seeds/UsersTableSeeder.php
Labels: database, in-review, task, week1

#8 Add templates admin show users
  app/Http/Controllers/Admin/UsersController.php
  public/css/admin/add.css
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#10 add layout edit user
  app/Http/Controllers/Admin/UsersController.php
  resources/lang/en/admin.php
  resources/lang/en/user.php
  resources/views/admin/home/index.blade.php
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/user/edit.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#11 Get List User
  app/Http/Controllers/Admin/UsersController.php
  app/User.php
  config/define.php
Labels: in-review, task, week1

#9 create-user
  app/Http/Controllers/Admin/UsersController.php
  app/Http/Requests/StoreUsers.php
  composer.json
  composer.lock
  database/migrations/2018_05_16_021651_default_role_to_users_table.php
  resources/lang/en/admin.php
  resources/lang/en/user.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/user/create.blade.php
  routes/web.php
Labels: in-review, task, week1

#12 show list users and change avatar ,product default
  database/seeds/ImagesTableSeeder.php
  database/seeds/OrderDetailsTableSeeder.php
  database/seeds/UserInfosTableSeeder.php
  public/css/admin/add.css
  public/images/products/default-product.jpg
  public/images/users/default-user-avatar.png
  resources/views/admin/user/index.blade.php
Labels: in-review, task, week1

#13 Get user info
  app/Http/Controllers/Admin/UsersController.php
  app/UserInfo.php
  config/define.php
  config/view.php
  public/css/admin/add.css
  resources/lang/en/errors.php
  resources/views/admin/errors/404.blade.php
  resources/views/admin/user/edit.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#18 Edit user validation
  app/Http/Controllers/Admin/UsersController.php
  app/Http/Requests/UpdateUsersRequest.php
  public/images/products/default-product.jpg
  resources/lang/en/message.php
  resources/views/admin/errors/error_validation.blade.php
  resources/views/admin/layout/message.blade.php
  resources/views/admin/user/edit.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#16 Delete User
  app/Http/Controllers/Admin/UsersController.php
  app/User.php
  app/UserInfo.php
  composer.json
  composer.lock
  config/app.php
  config/define.php
  database/migrations/2018_05_18_041105_create_deleted_at.php
  public/css/admin/add.css
  resources/lang/en/user.php
  resources/views/admin/layout/header.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#21 Test Delete User
  tests/Browser/Pages/Backend/User/DeleteUserTest.php
  tests/Browser/Pages/Backend/User/ListUserTest.php
Labels: in-review, task, week2

#17 search user with name
  app/Http/Controllers/Admin/UsersController.php
  app/SearchTrait.php
  app/User.php
  resources/views/admin/user/index.blade.php
Labels: in-review, task, week1

#20 Unit test edit user
  database/factories/ModelFactory.php
  resources/views/admin/user/index.blade.php
  tests/Browser/Pages/Backend/User/EditUserTest.php
Labels: in-review, task, week2

#23 Layout show category and Get Category
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  resources/lang/en/category.php
  resources/views/admin/category/index.blade.php
  resources/views/admin/layout/sidebar.blade.php
  routes/web.php
Labels: in-review, task, week2

#15 send-email-mailtrap
  .env.example
  app/Http/Controllers/Admin/UsersController.php
  app/Jobs/SendEmailJob.php
  app/Mail/SendEmail.php
  config/mail.php
  database/migrations/2018_05_21_023451_create_jobs_table.php
  resources/lang/en/message.php
  resources/lang/en/user.php
  resources/views/admin/user/index.blade.php
  resources/views/email/content.blade.php
  tests/Browser/Pages/Backend/User/EditUserTest.php
Labels: in-review, task, week1

#24 add layout list products and fix layout list users
  app/Http/Controllers/Admin/ProductsController.php
  public/images/products/default-product.jpg
  resources/lang/en/product.php
  resources/lang/en/user.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#25 add relationship model category and show list category
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  resources/views/admin/category/index.blade.php
Labels: in-review, task, week2

#26 Layout create products
  app/Http/Controllers/Admin/ProductsController.php
  resources/lang/en/product.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#27 Show product
  app/Http/Controllers/Admin/ProductsController.php
  app/Product.php
  config/define.php
  database/migrations/2018_05_23_152209_rename_products_column.php
  database/seeds/ProductsTableSeeder.php
  resources/views/admin/product/index.blade.php
Labels: in-review, task, week2

#28 update-column-user
  app/Http/Controllers/Admin/UsersController.php
  resources/lang/en/user.php
  resources/views/admin/user/create.blade.php
  resources/views/admin/user/index.blade.php
Labels: in-review, task, week2

#31 create-layout-post
  app/Http/Controllers/Admin/PostsController.php
  resources/lang/en/post.php
  resources/views/admin/post/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#30 write unit test show list products
  database/factories/ModelFactory.php
  tests/Browser/Pages/Backend/Product/ShowProductTest.php
Labels: in-review, task, week2

#34 delete product and fix unit test delete user
  app/Http/Controllers/Admin/ProductsController.php
  app/Image.php
  app/Product.php
  database/migrations/2018_05_24_081641_create_deleted_at_products.php
  public/js/admin/add.js
  resources/lang/en/message.php
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
  tests/Browser/Pages/Backend/User/DeleteUserTest.php
Labels: in-review, task, week2

#35 Unit test create user
  tests/Browser/Pages/Backend/User/CreateUserTest.php
Labels: in-review, task, week2

#32 Search list category
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  routes/web.php
Labels: in-review, task, week2

#29 test list category and add paginate
  database/factories/ModelFactory.php
  resources/views/admin/category/index.blade.php
  tests/Browser/Pages/Backend/Category/ListCategoryTest.php
Labels: in-review, task, week2

#37 show detail poduct
  app/Http/Controllers/Admin/ProductsController.php
  app/Image.php
  config/define.php
  public/css/admin/add.css
  resources/lang/en/product.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/product/show.blade.php
Labels: in-review, task, week2

#33 Create product
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Requests/CreateProductRequest.php
  app/Http/ViewComposers/CategoryComposer.php
  app/Image.php
  app/Providers/ComposerServiceProvider.php
  config/app.php
  resources/lang/en/message.php
  resources/views/admin/product/category.blade.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/index.blade.php
Labels: in-review, task, week2

#46 add layout show list orders
  app/Http/Controllers/Admin/OrdersController.php
  resources/lang/en/order.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/order/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#40 write unit test delete product
  resources/lang/en/message.php
  resources/views/admin/user/edit.blade.php
  tests/Browser/Pages/Backend/Product/DeleteProductTest.php
Labels: in-review, task, week2

#47 add layout update product and get product
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Requests/CreateProductRequest.php
  app/Providers/ComposerServiceProvider.php
  public/css/admin/add.css
  resources/lang/en/product.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/createCategory.blade.php
  resources/views/admin/product/edit.blade.php
  resources/views/admin/product/editCategory.blade.php
  resources/views/admin/product/index.blade.php
Labels: in-review, task, week 3

#43 write unit test create product
  app/Http/Controllers/Admin/ProductsController.php
  database/factories/ModelFactory.php
  resources/lang/en/product.php
  resources/views/admin/product/create.blade.php
  tests/Browser/Pages/Backend/Product/CreateProductTest.php
Labels: in-review, task, week 3

#51 fix layout home admin
  resources/lang/en/home.php
  resources/views/admin/home/index.blade.php
Labels: in-review, task, week 3

#52 layout create category
  app/Http/Controllers/Admin/CategoriesController.php
  app/Http/Requests/CategoryRequests.php
  resources/lang/en/category.php
  resources/views/admin/category/create.blade.php
  resources/views/admin/category/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#48 show list post
  app/Http/Controllers/Admin/PostsController.php
  app/Post.php
  database/factories/ModelFactory.php
  database/migrations/2018_05_28_082621_add_status_to_posts_table.php
  database/seeds/PostsTableSeeder.php
  resources/lang/en/post.php
  resources/views/admin/post/index.blade.php
Labels: in-review, task, week 3

#55 statistic: total products, total product orderd, total orderd, total re…
  app/Http/Controllers/Admin/HomeController.php
  app/Order.php
  resources/views/admin/home/index.blade.php
Labels: in-review, task, week 3

#56 Save category
  app/Http/Controllers/Admin/CategoriesController.php
  app/Http/Requests/CategoryRequests.php
  public/images/products/1527577878_2c9ef150b5e90fb54ba9a184e3547de1.jpg
  resources/lang/en/category.php
  resources/views/admin/category/create.blade.php
  routes/web.php
Labels: in-review, task, week 3

#54 Process status ajax
  app/Http/Controllers/Admin/PostsController.php
  app/Post.php
  public/images/posts/icons/accept.png
  public/images/posts/icons/exclamation.png
  public/images/products/1527577878_2c9ef150b5e90fb54ba9a184e3547de1.jpg
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/master.blade.php
  resources/views/admin/post/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#57 delete post
  app/Http/Controllers/Admin/PostsController.php
  resources/lang/en/message.php
  resources/views/admin/post/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#41 fix error important
  app/Http/Controllers/Admin/UsersController.php
  app/Http/Requests/StoreUsers.php
Labels: bug, in-review, week2

#58 add file css, js and fonts layout public
  public/css/public/blog.css
  public/css/public/bootstrap.min.css
  public/css/public/font-awesome.css
  public/css/public/owl.carousel.css
  public/css/public/owl.theme.css
  public/css/public/quick_view_popup.css
  public/css/public/style.css
  public/fonts/font-awesome/fontawesome-webfont3e6e.eot
  public/fonts/font-awesome/fontawesome-webfont3e6e.svg
  public/fonts/font-awesome/fontawesome-webfont3e6e.ttf
  public/fonts/font-awesome/fontawesome-webfont3e6e.woff
  public/fonts/font-awesome/fontawesome-webfontd41d.eot
  public/fonts/glyphicons-halflings-regular.eot
  public/fonts/glyphicons-halflings-regular.svg
  public/fonts/glyphicons-halflings-regular.ttf
  public/fonts/glyphicons-halflings-regular.woff
  public/fonts/glyphicons-halflings-regulard41d.eot
  public/fonts/lato/9k-RPmcnxYEPm8CNFsH2gg.woff
  public/fonts/lato/BVtM30trf7q_jfqYeHfjtA.woff
  public/fonts/lato/KT3KS9Aol4WfR6Vas8kNcg.woff
  public/fonts/lato/wkfQbvfT_02e2IWO3yYueQ.woff
  public/fonts/simple-line-icons/Simple-Line-Icons.eot
  public/fonts/simple-line-icons/Simple-Line-Icons.svg
  public/fonts/simple-line-icons/Simple-Line-Icons.ttf
  public/fonts/simple-line-icons/Simple-Line-Icons.woff
  public/fonts/simple-line-icons/Simple-Line-Iconsd41d.eot
  public/images/logo.png
  public/js/public/bootstrap.min.js
  public/js/public/cloud-zoom.js
  public/js/public/jquery.flexslider.js
  public/js/public/jquery.magnifying-zoom.js
  public/js/public/jquery.min.js
  public/js/public/main.js
  public/js/public/mobile-menu.js
  public/js/public/owl.carousel.min.js
Labels: in-review, task, week 3

#53 Edit product
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Requests/UpdateProductRequest.php
  composer.json
  composer.lock
  config/app.php
  public/js/admin/add.js
  public/js/messages.js
  resources/lang/en/message.php
  resources/lang/en/product.php
  resources/views/admin/layout/footer.blade.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/edit.blade.php
Labels: in-review, task, week 3

#66 Create migration level category
  database/migrations/2018_05_31_022145_add_level_to_categories_table.php
  database/seeds/CategoriesTableSeeder.php
  resources/views/admin/category/edit.blade.php
Labels: in-review, task, week 3

#64 show list orders
  app/Http/Controllers/Admin/OrdersController.php
  app/Order.php
  config/define.php
  resources/lang/en/order.php
  resources/views/admin/home/index.blade.php
  resources/views/admin/order/index.blade.php
Labels: in-review, task, week 3
