Repository AT-PHPIntership/food-drink, pull requests merged in 2018-06, with the labels that each got.

#63 fix show post and search post
  app/Http/Controllers/Admin/PostsController.php
  resources/lang/en/post.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/post/index.blade.php
Labels: in-review, task, week 3

#68 test delete post
  resources/views/admin/post/index.blade.php
  tests/Browser/Pages/Backend/Post/DeletePostTest.php
Labels: in-review, task, week 3

#62 Unit test edit product
  tests/Browser/Pages/Backend/Product/EditProductTest.php
Labels: in-review, task, week 3

#65 get category info
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  resources/views/admin/category/edit.blade.php
  resources/views/admin/category/index.blade.php
Labels: in-review, task, week 3

#61 statistic order, product for week, month and latest orders
  app/Http/Controllers/Admin/HomeController.php
  app/Order.php
  database/seeds/OrderDetailsTableSeeder.php
  resources/lang/en/home.php
  resources/views/admin/home/index.blade.php
Labels: in-review, task, week 3

#73 add master page user
  public/css/public/style.css
  public/images/logo.png
  resources/views/user/layout/footer.blade.php
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/master.blade.php
  resources/views/user/layout/nav.blade.php
  resources/views/user/layout/script.blade.php
  resources/views/user/layout/style.blade.php
Labels: in-review, task, week 3

#74 search order
  app/Http/Controllers/Admin/OrdersController.php
Labels: in-review, task, week 3

#69 show detail order
  app/Http/Controllers/Admin/OrdersController.php
  app/Http/Requests/UpdateUsersRequest.php
  database/migrations/2018_06_01_024844_change_user_infos_column.php
  public/css/admin/add.css
  resources/lang/en/order.php
  resources/views/admin/order/index.blade.php
  resources/views/admin/order/show.blade.php
  resources/views/admin/product/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#71 test show list post and search
  tests/Browser/Pages/Backend/Post/ListPostTest.php
Labels: in-review, task, week 3

#77 Test change status post
  tests/Browser/Pages/Backend/Post/TestChangeStatus.php
Labels: in-review, task, week 3

#72 change status order
  app/Http/Controllers/Admin/OrdersController.php
  app/Http/Requests/ChangeStatusRequest.php
  app/Order.php
  public/js/admin/add.js
  public/js/messages.js
  resources/lang/en/message.php
  resources/lang/en/order.php
  resources/views/admin/order/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#84 sort category
  app/Http/Controllers/Admin/CategoriesController.php
  app/Http/Requests/SortCategoryRequest.php
  resources/views/admin/category/index.blade.php
Labels: in-review, task, week 4

#85 create document api template
  docs/api-references/api.md
  resources/views/api-docs-builders/index.blade.php
  resources/views/api-docs.blade.php
  routes/web.php
Labels: in-review, task, week 4

#76 Delete category
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  public/images/products/1528192489_cdfe9fc7cf9cdf7eaaa722fb3bf95742.jpg
  public/images/products/1528192547_bfc2f9c4f1c3bf91b3fe29cd412186f4.jpg
  resources/lang/en/category.php
  resources/lang/en/order.php
  resources/views/admin/category/index.blade.php
  resources/views/admin/user/index.blade.php
  routes/web.php
Labels: in-review, task, week 3

#87 test update category
  tests/Browser/Pages/Backend/Category/UpdateCategoryTest.php
Labels: in-review, task, week 4

#88 update delete user
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Controllers/Admin/UsersController.php
  app/Order.php
  resources/lang/en/order.php
Labels: in-review, task, week 4

#94 fix layout master page frontend and move folder css, js, images frontend
  public/frontend/css/blog.css
  public/frontend/css/bootstrap.min.css
  public/frontend/css/font-awesome.css
  public/frontend/css/owl.carousel.css
  public/frontend/css/owl.theme.css
  public/frontend/css/quick_view_popup.css
  public/frontend/css/style.css
  public/frontend/fonts/font-awesome/fontawesome-webfont3e6e.eot
  public/frontend/fonts/font-awesome/fontawesome-webfont3e6e.svg
  public/frontend/fonts/font-awesome/fontawesome-webfont3e6e.ttf
  public/frontend/fonts/font-awesome/fontawesome-webfont3e6e.woff
  public/frontend/fonts/font-awesome/fontawesome-webfontd41d.eot
  public/frontend/fonts/glyphicons-halflings-regular.eot
  public/frontend/fonts/glyphicons-halflings-regular.svg
  public/frontend/fonts/glyphicons-halflings-regular.ttf
  public/frontend/fonts/glyphicons-halflings-regular.woff
  public/frontend/fonts/glyphicons-halflings-regulard41d.eot
  public/frontend/fonts/lato/9k-RPmcnxYEPm8CNFsH2gg.woff
  public/frontend/fonts/lato/BVtM30trf7q_jfqYeHfjtA.woff
  public/frontend/fonts/lato/KT3KS9Aol4WfR6Vas8kNcg.woff
  public/frontend/fonts/lato/wkfQbvfT_02e2IWO3yYueQ.woff
  public/frontend/fonts/simple-line-icons/Simple-Line-Icons.eot
  public/frontend/fonts/simple-line-icons/Simple-Line-Icons.svg
  public/frontend/fonts/simple-line-icons/Simple-Line-Icons.ttf
  public/frontend/fonts/simple-line-icons/Simple-Line-Icons.woff
  public/frontend/fonts/simple-line-icons/Simple-Line-Iconsd41d.eot
  public/frontend/images/logo.png
  public/frontend/js/bootstrap.min.js
  public/frontend/js/cloud-zoom.js
  public/frontend/js/jquery.flexslider.js
  public/frontend/js/jquery.magnifying-zoom.js
  public/frontend/js/jquery.min.js
  public/frontend/js/main.js
  public/frontend/js/mobile-menu.js
  public/frontend/js/owl.carousel.min.js
  resources/views/user/layout/master.blade.php
  resources/views/user/layout/script.blade.php
  resources/views/user/layout/style.blade.php
Labels: in-review, task, week 4

#91 sort user
  app/Http/Controllers/Admin/UsersController.php
  app/Http/Requests/SortUserRequest.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/user/index.blade.php
Labels: in-review, task, week 4

#89 Docs api product
  docs/api-references/product.md
  docs/api-references/sample.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week 4

#80 write unit test show list orders
  tests/Browser/Pages/Backend/Order/ListOrderTest.php
Labels: in-review, task, week 4

#92 sort-post
  app/Http/Controllers/Admin/PostsController.php
  app/Post.php
  app/Product.php
  composer.json
  composer.lock
  config/app.php
  resources/views/admin/post/index.blade.php
Labels: in-review, task, week 4

#95 layout home page frontend
  app/Http/Controllers/User/HomeController.php
  public/frontend/images/banner_drink.jpg
  public/frontend/images/banner_food.jpg
  resources/lang/en/home.php
  resources/views/user/home/index.blade.php
  resources/views/user/home/listDrink.blade.php
  resources/views/user/home/listFood.blade.php
  resources/views/user/home/topNewProduct.blade.php
  resources/views/user/home/topRateProduct.blade.php
  resources/views/user/layout/nav.blade.php
  routes/web.php
Labels: in-review, week 4, week1

#96 edit document api product
  docs/api-references/product.md
Labels: in-review, task, week 4

#97 Unit test show detail order
  app/User.php
  database/factories/ModelFactory.php
  tests/Browser/Pages/Backend/Order/ShowDetailOrderTest.php
Labels: in-review, task, week 4

#99 fix test all
  tests/Browser/Pages/Backend/Category/UpdateCategoryTest.php
  tests/Browser/Pages/Backend/Order/ListOrderTest.php
  tests/Browser/Pages/Backend/Order/ShowDetailOrderTest.php
Labels: in-review, task, week 4

#98 fix sort product, user, post, category
  app/Category.php
  app/Http/Controllers/Admin/CategoriesController.php
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Controllers/Admin/UsersController.php
  app/Post.php
  app/Product.php
  app/User.php
  resources/views/admin/category/index.blade.php
  resources/views/admin/post/index.blade.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/user/index.blade.php
  tests/Browser/Pages/Backend/Order/ListOrderTest.php
Labels: in-review, task, week 4

#90 api product
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/ProductController.php
  app/Http/Requests/SortApiProductRequest.php
  app/Traits/ApiResponse.php
  docs/api-references/product.md
  resources/lang/en/api.php
  routes/api.php
Labels: in-review, task, week 4

#100 sort order by id, name user, email user, total, date
  app/Http/Controllers/Admin/CategoriesController.php
  app/Http/Controllers/Admin/OrdersController.php
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Controllers/Admin/UsersController.php
  app/Http/Requests/SortCategoryRequest.php
  app/Http/Requests/SortProductRequest.php
  app/Http/Requests/SortUserRequest.php
  app/Order.php
  resources/views/admin/order/index.blade.php
Labels: in-review, task, week 4

#103 docs show product detail
  docs/api-references/product.md
Labels: in-review, task, week 4

#107 api show list post
  app/Http/Controllers/Api/ProductController.php
  config/define.php
  routes/api.php
Labels: in-review, task, week 5

#102 write unit test statistic
  app/Http/Controllers/Admin/HomeController.php
  tests/Browser/Pages/Backend/Home/Statistic.php
  tests/DuskTestCase.php
Labels: in-review, task, week 4

#104 api show detail product
  app/Http/Controllers/Api/ProductController.php
  app/Image.php
  routes/api.php
Labels: in-review, task, week 4

#108 api list category
  app/Category.php
  app/Http/Controllers/Api/CategoryController.php
  routes/api.php
Labels: in-review, task, week 5

#111 filter name product
  app/Http/Controllers/Api/ProductController.php
  app/Http/Requests/SortApiProductRequest.php
Labels: in-review, task, week 5

#112 fix document product, apiResponser, productController
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/CategoryController.php
  app/Http/Controllers/Api/ProductController.php
  app/Http/Requests/Api/SortApiProductRequest.php
  app/Traits/ApiResponse.php
  app/Traits/ApiResponser.php
  docs/api-references/product.md
Labels: in-review, task, week 5

#110 layout login
  app/Http/Controllers/Home/LoginController.php
  public/frontend/css/style.css
  resources/lang/en/login.php
  resources/views/public/pages/login.blade.php
  routes/web.php
Labels: in-review, task, week 5

#115 filter price
  app/Http/Controllers/Api/ProductController.php
  app/Http/Requests/Api/SortApiProductRequest.php
Labels: in-review, task, week 5

#117 write document api show list posts
  docs/api-references/post.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week 5

#121 write document api get user infomation
  docs/api-references/user.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week 5

#118 add docs delete post
  database/migrations/2018_06_14_025528_change_rate_and_content_column.php
  docs/api-references/post.md
  docs/api-references/user.md
Labels: in-review, task, week 5

#123 write document api order detail
  docs/api-references/order.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week 5

#125 docs api filter product by name
  docs/api-references/product.md
Labels: in-review, task, week 5

#128 add layout filter
  app/Http/Controllers/User/FilterController.php
  public/frontend/css/add.css
  public/frontend/images/checkbox.png
  resources/lang/en/product.php
  resources/lang/en/sidebar.php
  resources/views/user/filter/index.blade.php
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/sidebar.blade.php
  resources/views/user/layout/style.blade.php
  routes/web.php
Labels: in-review, task, week 5

#119 Test api categories
  tests/Feature/Api/listCategoriesTest.php
Labels: in-review, task, week 5

#124 docs filter price
  docs/api-references/product.md
Labels: in-review, task, week 5

#114 init passport for user login
  app/Http/Controllers/Api/LoginController.php
  app/Http/Controllers/Api/UserController.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  resources/lang/en/login.php
  routes/api.php
Labels: in-review, task, week 5

#127 Layout user info
  app/Http/Controllers/User/UserController.php
  resources/views/user/profile/userProfile.blade.php
  routes/web.php
Labels: in-review, task, week 5

#120 Docs add post
  docs/api-references/post.md
Labels: in-review, task, week 5

#132 use api user login
  public/js/user/userLogin.js
  resources/views/public/pages/login.blade.php
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/script.blade.php
Labels: in-review, task, week6

#136 fix docs and api user info
  app/Http/Controllers/Api/ProfileController.php
  docs/api-references/post.md
  docs/api-references/user.md
  routes/api.php
Labels: in-review, task, week6

#139 layout post of product
  resources/views/user/post/postOfProduct.blade.php
Labels: in-review, task, week6

#143 use api post of product
  public/css/user/add.css
  public/js/user/showPostOfProduct.js
  resources/views/user/layout/script.blade.php
  resources/views/user/layout/style.blade.php
  resources/views/user/post/postOfProduct.blade.php
Labels: in-review, task, week6

#141 change url home
  public/js/user/userLogin.js
  routes/web.php
  tests/Browser/ExampleTest.php
Labels: bug, in-review, week6

#122 api delete post
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/PostController.php
  app/Traits/ApiResponser.php
  resources/lang/en/api.php
  routes/api.php
Labels: in-review, task, week 5

#138 add to cart
  public/js/user/addCart.js
  public/js/user/showProductHomePage.js
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/script.blade.php
Labels: in-review, task, week6

#133 Use api user info
  public/js/user/hidenLoginAndProfile.js
  public/js/user/showProfileUser.js
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/script.blade.php
  resources/views/user/profile/userProfile.blade.php
Labels: in-review, task, week6

#147 test product detail
  tests/Feature/Api/productDetailTest.php
Labels: in-review, task, week6

#148 layout category
  public/css/user/add.css
  public/js/user/slideToggle.js
  resources/views/user/layout/sidebar.blade.php
Labels: in-review, task, week6

#145 Use api show list product
  app/Http/Controllers/User/FilterController.php
  app/Http/Controllers/User/ProductsController.php
  public/js/showListProducts.js
  resources/views/user/product/index.blade.php
  routes/web.php
Labels: in-review, task, week6

#146 View cart
  app/Http/Controllers/User/CartController.php
  public/frontend/css/add.css
  public/js/messages.js
  public/js/user/viewCart.js
  resources/lang/en/cart.php
  resources/views/user/cart/index.blade.php
  resources/views/user/layout/header.blade.php
  routes/web.php
Labels: in-review, task, week6

#151 fix api show posts: paginate posts
  app/Http/Controllers/Api/ProductController.php
Labels: in-review, task, week6

#153 use api list category
  public/css/user/add.css
  public/js/user/showListCategory.js
  public/js/user/slideToggle.js
  resources/views/user/layout/sidebar.blade.php
Labels: in-review, task, week6

#155 Api create post
  app/Http/Controllers/Api/PostController.php
  app/Http/Requests/Api/CreatePostRequest.php
  routes/api.php
Labels: in-review, task, week6

#156 fix bug middleware admin
  app/Http/Middleware/AdminMiddleWare.php
  routes/web.php
Labels: bug, in-review, week6

#131 docs api register
  docs/api-references/user.md
Labels: in-review, task, week6

#159 fix docs api filter
  docs/api-references/product.md
Labels: bug, in-review, week6

#158 fix api filter price product
  app/Http/Controllers/Api/ProductController.php
Labels: bug, in-review

#144 view more product at homepage by category
  app/Http/Controllers/Api/ProductController.php
  public/frontend/css/add.css
  public/js/user/showProductHomePage.js
  resources/lang/en/home.php
  resources/views/user/home/index.blade.php
Labels: in-review, task, week6

#154 use api product filter
  public/frontend/css/add.css
  public/js/user/showListProducts.js
  resources/views/user/layout/script.blade.php
  resources/views/user/layout/sidebar.blade.php
  resources/views/user/product/index.blade.php
Labels: in-review, task, week6

#149 write unit test api show list product
  tests/Feature/Api/ListProductTest.php
Labels: in-review, task, week6

#163 edit document, api show post and layout show post
  app/Http/Controllers/Api/ProductController.php
  app/Http/Requests/Api/SortApiPostRequest.php
  docs/api-references/post.md
  public/js/user/showPostOfProduct.js
Labels: in-review, task, week6

#162 write document api update profile
  docs/api-references/user.md
Labels: in-review, task, week6

#152 Layout add post and fix layout show post
  app/Http/Controllers/User/ProductController.php
  app/Http/Controllers/User/ProductsController.php
  public/js/user/showProductHomePage.js
  resources/lang/en/product.php
  resources/views/user/layout/script.blade.php
  resources/views/user/product/show.blade.php
  routes/web.php
Labels: in-review, task, week6

#165 docs api show order
  docs/api-references/order.md
Labels: bug, in-review, week6

#164 fix api create post
  app/Http/Controllers/Api/PostController.php
  app/Http/Requests/Api/CreatePostRequest.php
  app/Order.php
  resources/lang/en/api.php
Labels: in-review, task, week6

#160 Api register
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/RegisterController.php
  resources/lang/en/api.php
  routes/api.php
Labels: in-review, task, week6

#166 Use api filter product by category
  public/frontend/css/add.css
  public/js/user/showListCategory.js
  public/js/user/showListProducts.js
  resources/lang/en/sidebar.php
  resources/views/user/layout/sidebar.blade.php
Labels: in-review, task, week6

#169 fix view more product homepage
  public/js/user/showProductHomePage.js
Labels: in-review, task, week6

#168 Use api add post
  app/Http/Controllers/Api/PostController.php
  public/js/messages.js
  public/js/user/addPost.js
  resources/lang/en/product.php
  resources/views/user/product/show.blade.php
Labels: in-review, task, week6

#170 fix show all products
  public/frontend/css/add.css
  public/js/user/showListProducts.js
  resources/lang/en/home.php
  resources/lang/en/product.php
  resources/lang/en/sidebar.php
  resources/views/user/layout/nav.blade.php
  resources/views/user/layout/script.blade.php
  resources/views/user/layout/sidebar.blade.php
  resources/views/user/product/index.blade.php
Labels: in-review, task, week 7

#171 update layout admin
  app/Http/Controllers/Admin/PostsController.php
  app/Post.php
  resources/lang/en/post.php
  resources/lang/en/user.php
  resources/views/admin/category/create.blade.php
  resources/views/admin/category/edit.blade.php
  resources/views/admin/category/index.blade.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/order/index.blade.php
  resources/views/admin/post/index.blade.php
  resources/views/admin/product/create.blade.php
  resources/views/admin/product/edit.blade.php
  resources/views/admin/product/index.blade.php
  resources/views/admin/user/create.blade.php
  tests/Browser/Pages/Backend/Post/ListPostTest.php
Labels: in-review, task, week 7

#172 Layout product detail
  resources/lang/en/product.php
  resources/views/user/product/index.blade.php
  resources/views/user/product/show.blade.php
Labels: in-review, task, week 7

#173 api-update-user
  app/Http/Controllers/Api/ProfileController.php
  app/Http/Requests/Api/UpdateProfileRequest.php
  resources/lang/en/api.php
  routes/api.php
Labels: in-review, task, week 7

#175 Use api detail product
  public/js/messages.js
  public/js/user/showProductDetail.js
  resources/views/user/product/show.blade.php
Labels: in-review, task, week 7

#178 fix document api show order detail
  docs/api-references/order.md
Labels: in-review, task, week 7

#177 fix use api add post
  app/Http/Requests/Api/CreatePostRequest.php
  public/js/messages.js
  public/js/user/addPost.js
  resources/lang/en/product.php
Labels: in-review, task, week 7

#179 Update post
  app/Http/Controllers/Admin/PostsController.php
Labels: bug, in-review, week 7

#181 fix docs api show order
  docs/api-references/order.md
Labels: bug, task, week 7

#184 create table notes and model note
  app/Note.php
  app/Order.php
  app/User.php
  database/migrations/2018_06_28_095209_create_notes_table.php
Labels: in-review, task, week 7

#185 send email change status order
  app/Http/Controllers/Admin/OrdersController.php
  app/Mail/ChangeStatusOrderMail.php
  resources/views/email/content.blade.php
  resources/views/email/order-change-status-mail.blade.php
Labels: in-review, task, week 7

#182 layout-register
  app/Http/Controllers/Home/RegisterController.php
  resources/lang/en/user.php
  resources/views/user/register/register.blade.php
  routes/web.php
Labels: in-review, task, week 7

#157 use api logout
  public/js/user/hidenLoginAndProfile.js
  public/js/user/masterPage.js
  resources/lang/en/home.php
  resources/views/user/layout/header.blade.php
  resources/views/user/layout/script.blade.php
Labels: in-review, task, week6

#187 Register user
  app/Http/Requests/StoreUsers.php
  public/js/user/register.js
  resources/lang/en/home.php
  resources/views/user/layout/header.blade.php
  resources/views/user/register/register.blade.php
Labels: in-review, task, week 7

#183 Api show order
  app/Http/Controllers/Api/OrderController.php
  app/Http/Requests/Api/SortOrderRequest.php
  app/Order.php
  routes/api.php
Labels: in-review, task, week 7
